name: phpmailer
recipe: lamp
config:
  webroot: .
  php: '8.2'
proxy:
  appserver:
    - phpmailer.lndo.site
  mailpit:
    - mailpit.phpmailer.lndo.site
  qmail:
    - qmail.phpmailer.lndo.site
services:
  appserver:
    xdebug: true
    config:
      php: .lando/php.ini
    build_as_root:
      - apt-get update
      - apt-get install -y netcat-openbsd
    overrides:
      depends_on:
        - mailpit
  mailpit:
    type: mailpit
    mailFrom:
      - appserver
    overrides:
      environment:
        MP_SMTP_RELAY_CONFIG: /app/smtp-relay.yml
      depends_on:
        - postfix
  postfix:
    type: compose
    overrides:
      build:
        context: .
        dockerfile: Dockerfile.postfix
      user: root
      command: ["bash","-lc","/usr/local/bin/postfix-start.sh"]
  qmail:
    type: compose
    overrides:
      build:
        context: .
        dockerfile: Dockerfile.qmail
      user: root
      command: ["bash","-lc","svscan /service"]
      environment:
        XDEBUG_CONFIG: client_host=host.lando.internal
      volumes:
        - ./.lando/php-qmail.ini:/etc/php/8.2/cli/conf.d/99-xdebug.ini:ro
    scanner: false   
  appserver-nombstring:
    type: compose
    config:
      php: .lando/php.ini
    overrides:
      build:
        context: .
        dockerfile: Dockerfile.nombstring
      command: ["bash","-lc","sleep infinity"]
      working_dir: /app
      user: root
      volumes:
        - ./:/app
      depends_on:
        - mailpit
  appserver-noopenssl:
    type: compose
    overrides:
      build:
        context: .
        dockerfile: Dockerfile.noopenssl
      command: ["bash","-lc","sleep infinity"]
      working_dir: /app
      user: root
      volumes:
        - ./:/app
      depends_on:
        - mailpit
tooling:
  test:
    service: appserver
    cmd: bash -lc './scripts/lando-test.sh default -- --exclude-group nombstring,languages,dkim,qmail'
  test-all:
    service: appserver
    cmd: bash -lc './scripts/lando-test.sh default -- "$@"'
  test-nombstring:
    service: appserver-nombstring
    cmd: bash -lc './scripts/lando-test.sh nombstring -- "$@"'
  test-noopenssl: # TODO: Remove dkim group, add groups to no openssl tests
    service: appserver-noopenssl
    cmd: bash -lc './scripts/lando-test.sh noopenssl -- "$@"'
  test-qmail:
    service: qmail
    cmd: bash -lc './scripts/lando-test.sh qmail -- --filter MailTransportTest'