name: phpmailer
recipe: lamp
config:
  webroot: .
  php: '8.2'
proxy:
  appserver:
    - phpmailer.lndo.site
  mailpit:
    - mailpit.phpmailer.lndo.site
services:
  mailpit:
    type: mailpit
    mailFrom:
      - appserver
    overrides:
      environment:
        MP_SMTP_RELAY_CONFIG: /app/smtp-relay.yml
      depends_on:
        - postfix
  postfix:
    type: compose
    overrides:
      build:
        context: .
        dockerfile: Dockerfile.postfix
      user: root
      command: ["bash","-lc","/usr/local/bin/postfix-start.sh"]
  appserver-nombstring:
    type: compose
    overrides:
      build:
        context: .
        dockerfile: Dockerfile.nombstring
      command: ["bash","-lc","sleep infinity"]
      working_dir: /app
      user: root
      volumes:
        - ./:/app
      depends_on:
        - postfix
tooling:
  test:
    service: appserver
    cmd: bash -lc './scripts/lando-test.sh'
  test-nombstring:
    service: appserver-nombstring
    cmd: bash  -lc './scripts/lando-test.sh nombstring'
  test-noopenssl:
    service: appserver-noopenssl
    cmd: bash  -lc './scripts/lando-test.sh openssl'